In [ ]:
!pip install transformers

Collecting transformers
  Downloading transformers-5.13.0-py3-none-any.whl.metadata (32 kB)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Downloading huggingface_hub-1.22.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (2.4.3)
Requirement already satisfied: packaging>=20.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (6.0.2)
Collecting regex>=2025.10.22 (from transformers)
  Downloading regex-2026.6.28-cp313-cp313-win_amd64.whl.metadata (41 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl.metadata (7.4 kB)
Requirement already satisfied: typer in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (0.9.0)
Collecting safetensors>=0.8.0 (from transformers)
  Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: tqdm>=4.60 in c:\users\kisha\anaconda3\lib\site-packages (from transformers) (4.67.1)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.2)
Collecting hf-xet<2.0.0,>=1.5.1 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl.metadata (4.9 kB)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: colorama in c:\users\kisha\anaconda3\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers) (0.4.6)
Requirement already satisfied: anyio in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.7.0)
Requirement already satisfied: certifi in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\kisha\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\kisha\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.0)
Downloading transformers-5.13.0-py3-none-any.whl (11.5 MB)
   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   -- ------------------------------------- 0.8/11.5 MB 5.2 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.5 MB 5.3 MB/s eta 0:00:02
   ----------- ---------------------------- 3.4/11.5 MB 5.7 MB/s eta 0:00:02
   ---------------- ----------------------- 4.7/11.5 MB 6.0 MB/s eta 0:00:02
   --------------------- ------------------ 6.3/11.5 MB 6.2 MB/s eta 0:00:01
   ------------------------ --------------- 7.1/11.5 MB 5.9 MB/s eta 0:00:01
   ----------------------------- ---------- 8.4/11.5 MB 5.9 MB/s eta 0:00:01
   --------------------------------- ------ 9.7/11.5 MB 5.9 MB/s eta 0:00:01
   -------------------------------------- - 11.0/11.5 MB 6.0 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 6.0 MB/s eta 0:00:00
Downloading huggingface_hub-1.22.0-py3-none-any.whl (765 kB)
   ---------------------------------------- 0.0/765.1 kB ? eta -:--:--
   ---------------------------------------- 765.1/765.1 kB 7.0 MB/s eta 0:00:00
Downloading click-8.4.2-py3-none-any.whl (119 kB)
Downloading hf_xet-1.5.1-cp37-abi3-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ------------- -------------------------- 1.3/4.0 MB 7.5 MB/s eta 0:00:01
   ----------------------- ---------------- 2.4/4.0 MB 7.0 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.0 MB 5.7 MB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 5.5 MB/s eta 0:00:00
Downloading tokenizers-0.22.2-cp39-abi3-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --------------- ------------------------ 1.0/2.7 MB 5.7 MB/s eta 0:00:01
   ------------------- -------------------- 1.3/2.7 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 4.6 MB/s eta 0:00:00
Downloading regex-2026.6.28-cp313-cp313-win_amd64.whl (277 kB)
Downloading safetensors-0.8.0-cp310-abi3-win_amd64.whl (355 kB)
Installing collected packages: safetensors, regex, hf-xet, click, huggingface-hub, tokenizers, transformers

  Attempting uninstall: regex

    Found existing installation: regex 2024.11.6

    Uninstalling regex-2024.11.6:

      Successfully uninstalled regex-2024.11.6

   ----- ---------------------------------- 1/7 [regex]
   ----------- ---------------------------- 2/7 [hf-xet]
  Attempting uninstall: click
   ----------- ---------------------------- 2/7 [hf-xet]
    Found existing installation: click 8.1.8
   ----------- ---------------------------- 2/7 [hf-xet]
    Uninstalling click-8.1.8:
   ----------- ---------------------------- 2/7 [hf-xet]
      Successfully uninstalled click-8.1.8
   ----------- ---------------------------- 2/7 [hf-xet]
   ----------------- ---------------------- 3/7 [click]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------- ----------------- 4/7 [huggingface-hub]
   ---------------------------- ----------- 5/7 [tokenizers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------- ----- 6/7 [transformers]
   ---------------------------------------- 7/7 [transformers]

Successfully installed click-8.4.2 hf-xet-1.5.1 huggingface-hub-1.22.0 regex-2026.6.28 safetensors-0.8.0 tokenizers-0.22.2 transformers-5.13.0

In [2]:
!pip install "transformers[torch]"

Requirement already satisfied: transformers[torch] in c:\users\kisha\anaconda3\lib\site-packages (5.13.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (1.22.0)
Requirement already satisfied: numpy>=1.17 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (2.4.3)
Requirement already satisfied: packaging>=20.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (0.22.2)
Requirement already satisfied: typer in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (0.9.0)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (4.67.1)
Requirement already satisfied: torch>=2.4 in c:\users\kisha\anaconda3\lib\site-packages (from transformers[torch]) (2.11.0)
Collecting accelerate>=1.1.0 (from transformers[torch])
  Downloading accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\kisha\anaconda3\lib\site-packages (from huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.15.0)
Requirement already satisfied: colorama in c:\users\kisha\anaconda3\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.4.6)
Requirement already satisfied: anyio in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (4.7.0)
Requirement already satisfied: certifi in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (2026.5.20)
Requirement already satisfied: httpcore==1.* in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.0.9)
Requirement already satisfied: idna in c:\users\kisha\anaconda3\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (3.7)
Requirement already satisfied: h11>=0.16 in c:\users\kisha\anaconda3\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (0.16.0)
Requirement already satisfied: psutil in c:\users\kisha\anaconda3\lib\site-packages (from accelerate>=1.1.0->transformers[torch]) (5.9.0)
Requirement already satisfied: setuptools<82 in c:\users\kisha\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (72.1.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\kisha\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\users\kisha\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\kisha\anaconda3\lib\site-packages (from torch>=2.4->transformers[torch]) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\kisha\anaconda3\lib\site-packages (from sympy>=1.13.3->torch>=2.4->transformers[torch]) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\kisha\anaconda3\lib\site-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers[torch]) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\kisha\anaconda3\lib\site-packages (from jinja2->torch>=2.4->transformers[torch]) (3.0.2)
Downloading accelerate-1.14.0-py3-none-any.whl (389 kB)
Installing collected packages: accelerate
Successfully installed accelerate-1.14.0

In [1]:
import pandas as pd
from transformers import T5Tokenizer, Trainer, TrainingArguments, T5ForConditionalGeneration

In [2]:
train_data = pd.read_csv("samsumdataset/samsum-train.csv")
val_data = pd.read_csv("samsumdataset/samsum-validation.csv")

In [3]:
train_data.head()

,id,dialogue,summary
0,13818513,Amanda: I baked cookies. Do you want some?\r\...,Amanda baked cookies and will bring Jerry some...
1,13728867,Olivia: Who are you voting for in this electio...,Olivia and Olivier are voting for liberals in ...
2,13681000,"Tim: Hi, what's up?\r\nKim: Bad mood tbh, I wa...",Kim may try the pomodoro technique recommended...
3,13730747,"Edward: Rachel, I think I'm in ove with Bella....",Edward thinks he is in love with Bella. Rachel...
4,13728094,Sam: hey overheard rick say something\r\nSam:...,"Sam is confused, because he overheard Rick com..."

In [4]:
train_data['dialogue'][0]

"Amanda: I baked  cookies. Do you want some?\r\nJerry: Sure!\r\nAmanda: I'll bring you tomorrow :-)"

In [5]:
train_data.sample(10)

,id,dialogue,summary
7777,13730890,Fran: I can't find my boarding pass. Have you ...,Jim helps Fran find her boarding pass in the d...
13792,13730005,"Randy: Hi, I'm writing about the stroller you ...",Randy is interested in the stroller Todd is se...
3635,13810144,"Hailey: heyoooo, I got an important question f...",Hailey invites Peter for a house-warming part ...
10335,13681683,Melissa: Is there any more info on Grandma?\r\...,Grandma is recovering after a health incident....
44,13682379,Linda: I'm going to have my room painted\r\nLi...,"According to Brian, colors that match Linda's ..."
7042,13818836,Marie: would any of you be a dear and put the ...,Vanessa can put the pot with soup on the stove...
14576,13728361-1,"Ian: U on campus? Lunch at AW?\r\nViola: Yes, ...",Viola invited Ian for lunch with her parents. ...
7250,13680801,Nora: how r u? How r u feeling?\r\nJane: same ...,"Jane was at the doctor, she is 7 months pregna..."
8124,13829671,Kim: did you bring back the car?\r\nJane: yes\...,Jane brought back the car.
3741,13817611,"Kai: did you know, that there are several medi...",Rapunzel syndrome is one of the medical condit...

In [6]:
print("train", train_data.shape)
print("validation", val_data.shape)

train (14732, 3)
validation (818, 3)

In [7]:
# random sampling

train_data = train_data.sample(n=4000, random_state=42).reset_index(drop=True)
val_data = val_data.sample(n=500, random_state=42).reset_index(drop=True)

In [8]:
train_data.shape

(4000, 3)

In [9]:
val_data.shape

(500, 3)

### data pre-processing

In [11]:
import re

def clean_data(text):
    text = re.sub(r"\r\n", " ", text) #lines
    text = re.sub(r"\s+", " ", text) #spces
    text = re.sub(r"<.*?>", " ", text) #html tags
    text.strip().lower()
    return text

In [12]:
train_data["dialogue"] = train_data["dialogue"].apply(clean_data)
train_data["summary"] = train_data["summary"].apply(clean_data)

val_data["dialogue"] = val_data["dialogue"].apply(clean_data)
val_data["summary"] = val_data["summary"].apply(clean_data)

In [13]:
train_data["dialogue"][0]

"Violet: hi! i came across this Austin's article and i thought that you might find it interesting Violet:   Claire: Hi! :) Thanks, but I've already read it. :) Claire: But thanks for thinking about me :)"

### tokenization

In [14]:
tokenizer = T5Tokenizer.from_pretrained("t5-small")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json:   0%|          | 0.00/2.32k [00:00<?, ?B/s]

c:\Users\kisha\anaconda3\envs\ai\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\kisha\.cache\huggingface\hub\models--t5-small. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.39M [00:00<?, ?B/s]

In [15]:
# raw data => tokenized inputsfor fine-tuning

def tokenize(data):
    inputs = tokenizer(data["dialogue"], padding="max_length", max_length = 512, truncation=True)
    targets = tokenizer(data["summary"], padding="max_length", max_length = 158, truncation=True)
    
    inputs["labels"] = targets["input_ids"] # token ids => add to input as labels
    return inputs

In [16]:
train_dataset = train_data.apply(tokenize, axis=1).tolist()
val_dataset = val_data.apply(tokenize, axis=1).tolist()

In [20]:
train_dataset[0]

{'input_ids': [28866, 10, 7102, 55, 3, 23, 764, 640, 48, 8513, 31, 7, 1108, 11, 3, 23, 816, 24, 25, 429, 253, 34, 1477, 28866, 10, 19542, 10, 2018, 55, 3, 10, 61, 1333, 6, 68, 27, 31, 162, 641, 608, 34, 5, 3, 10, 61, 19542, 10, 299, 2049, 21, 1631, 81, 140, 3, 10, 61, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [28866, 1622, 19542, 8513, 31, 7, 1108, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

In [18]:
# inputs ids - dialogue => tokenize ids

# 1 => End of sequance, 0 => padding

# attention masks
# labels - target => summary

In [23]:
len(train_dataset[0]["input_ids"])

512

In [25]:
type(train_dataset)
type(val_dataset)

list

### Working with model

In [26]:
# NLP => generation task

model = T5ForConditionalGeneration.from_pretrained("t5-small")

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/242M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [27]:
# fine - tune

import torch

if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print("device: ", device)
model.to(device)

device:  cuda

T5ForConditionalGeneration(
  (shared): Embedding(32128, 512)
  (encoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (decoder): T5Stack(
    (embed_tokens): Embedding(32128, 512)
    (block): ModuleList(
      (0): T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
              (relative_attention_bias): Embedding(32, 8)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
      (1-5): 5 x T5Block(
        (layer): ModuleList(
          (0): T5LayerSelfAttention(
            (SelfAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (1): T5LayerCrossAttention(
            (EncDecAttention): T5Attention(
              (q): Linear(in_features=512, out_features=512, bias=False)
              (k): Linear(in_features=512, out_features=512, bias=False)
              (v): Linear(in_features=512, out_features=512, bias=False)
              (o): Linear(in_features=512, out_features=512, bias=False)
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (2): T5LayerFF(
            (DenseReluDense): T5DenseActDense(
              (wi): Linear(in_features=512, out_features=2048, bias=False)
              (wo): Linear(in_features=2048, out_features=512, bias=False)
              (dropout): Dropout(p=0.1, inplace=False)
              (act): ReLU()
            )
            (layer_norm): T5LayerNorm()
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (final_layer_norm): T5LayerNorm()
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (lm_head): Linear(in_features=512, out_features=32128, bias=False)
)

In [28]:
# training arguements 

training_args = TrainingArguments(
    output_dir = "./results",

    num_train_epochs=6,
    weight_decay=0.01,

    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,

    eval_strategy="epoch",
    save_strategy="epoch",

    warmup_steps=500
    # 0 => lr default 
)

In [29]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

In [30]:
# train the model

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=3000, training_loss=0.9670548909505209, metrics={'train_runtime': 3200.4342, 'train_samples_per_second': 7.499, 'train_steps_per_second': 0.937, 'total_flos': 3248203235328000.0, 'train_loss': 0.9670548909505209, 'epoch': 6.0})

In [32]:
# model load => fine-tune => savethe model

In [33]:
model.save_pretrained("./saved_summary_model")
tokenizer.save_pretrained("./saved_summary_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./saved_summary_model\\tokenizer_config.json',
 './saved_summary_model\\tokenizer.json')

In [35]:
model = T5ForConditionalGeneration.from_pretrained("./saved_summary_model")
tokenizer = T5Tokenizer.from_pretrained("./saved_summary_model")

Loading weights:   0%|          | 0/131 [00:00<?, ?it/s]

### test the core logic for summarization

In [40]:
def summarize_dialogue(dialogue):
    dialogue = clean_data(dialogue) # clean

    # tokenize
    inputs = tokenizer(
        dialogue,
        padding="max_length",
        max_length=512,
        truncation=True,
        return_tensors="pt"
    ).to(device)

    # generate the summary => token ids
    model.to(device)
    targets = model.generate(
        input_ids=inputs["input_ids"],
        attention_mask=inputs["attention_mask"],
        max_length=150,
        num_beams=4,
        early_stopping=True
    )
    
    # decoded our output
    summary = tokenizer.decode(targets[0], skip_special_tokens=True) # EOS, SEP
    return summary

In [41]:
test_dialogue = """ 
Reporter: In today's technology news, artificial intelligence continues to expand rapidly across industries, from healthcare to finance and education. Recent reports suggest that AI adoption has significantly increased over the past few years.

Reporter: Companies are investing heavily in machine learning systems to automate tasks, improve decision-making, and enhance customer experiences. However, this growth has also raised questions about job displacement and ethical concerns.

Expert: AI systems are becoming more capable due to advances in deep learning and access to large datasets. These models can now perform complex tasks such as language understanding, image recognition, and even code generation.

Expert: At the same time, there are valid concerns about bias in AI models, as they often reflect the data they are trained on. Ensuring fairness and transparency is becoming a key area of research.

Reporter: Governments and organizations are beginning to introduce regulations to guide the development and deployment of AI technologies. The goal is to balance innovation with accountability.

Expert: Another challenge is explainability. Many modern AI systems, especially deep neural networks, operate as “black boxes,” making it difficult to understand how decisions are made.

Reporter: Experts also highlight the importance of responsible AI development, including data privacy, security, and long-term societal impact.

Expert: Looking ahead, collaboration between researchers, policymakers, and industry leaders will be crucial to ensure that AI systems are developed and used in a safe and beneficial way.
"""

summary = summarize_dialogue(test_dialogue)

print("Summary: ", summary)

Summary:  AI adoption has significantly increased over the past few years. Experts are concerned about bias in AI models because they reflect the data they are trained on.